version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    container_name: 'gitlab-server'
    restart: always
    hostname: 'my-hostname.org'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://my-external-url.com'
        letsencrypt['enable'] = true
        letsencrypt['contact_emails'] = ['email@example.com']
        letsencrypt['auto_renew'] = true
        letsencrypt['auto_renew_hour'] = "12"
        letsencrypt['auto_renew_minute'] = "30"
        letsencrypt['auto_renew_day_of_month'] = "*/7"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "my-smtp-server.com"
        gitlab_rails['smtp_user_name'] = "email@example.com"
        gitlab_rails['smtp_password'] = "email_password"
        gitlab_rails['smtp_domain'] = "example.com"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['gitlab_email_from'] = 'from-email@example.com'
        gitlab_rails['gitlab_email_reply_to'] = 'reply-to-email@example.com'
        gitlab_rails['backup_keep_time'] = 604800
    ports:
    - '80:80'
    - '443:443'
    - '22:22'
    - '587:587'
    volumes:
    - '$GITLAB_HOME:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
    - '$GITLAB_HOME/secret-backups:/etc/gitlab/config_backup'
    shm_size: '256m'